### ISSUE TITLE
if statements in paginate.checkPage()

### ISSUE THREAD

**Issue by dogsGhost** [dunnbro/pagination#10]
You can select multiple individual elements to do the same action to in jquery:

```
 $('#js-first, #js-previous').prop('disabled', true);
```

Knowing this you can refactor these statements, which may show an easier way to write this.

**Comment by dunnbro** [comment]
Condensed these statements as specified.

**Comment by dogsGhost** [comment]
Consolidate `$('#js-first, #js-last, #js-previous, #js-next')` selector and refactor to enable all inputs _first_, then do the `if` checks. Also check variable assignments.
