### ISSUE TITLE
invalid hash breaks page

### ISSUE THREAD

**Issue by dogsGhost** [dunnbro/pagination#16]
If the url hash is passed as  '#section11' (a value outside the total number of sections) no sections are made visible. Add a check to make sure the number you're getting from the hash is a valid section before doing anything with it.

Since this is a bug fix, don't forget to increment the PATCH value for the version in readme.md and package.json

**Comment by dunnbro** [comment]
I have a validhash check in hashListener, what is the expected behavior if
an invalid hash is typed in?

**Comment by dogsGhost** [comment]
Since the hash is invalid, it would be the same as if no hash was passed. The check in `hashListener()` looks good, I think you might need something in `displaySetup()` as that is what runs on page load.

**Comment by dunnbro** [comment]
Ok. So if an invalid hash is typed in, all storysections should be hidden?

**Comment by dogsGhost** [comment]
No, it would ignore the invalid hash and run as normal, so section 1 would show.

**Comment by dogsGhost** [comment]
Moving this to milestone 2 as v2 development may resolve this issue.

**Comment by dunnbro** [comment]
Modified displaySetup to address this.

**Comment by dogsGhost** [comment]
This is now adding the hash `#section1` on page load even if there's no hash on the url initially.
This is undesired, so hash should be added if there isn't one already.
Also the commit for this fix seems to have created the bug in issue #19 as well.

**Comment by dunnbro** [comment]
The hash `#section1` no longer appears on page load. 
If an invalid hash is entered, the hash value is cleared completely.

**Comment by dogsGhost** [comment]
To clarify, an invalid hash should leave the paginated area _completely unchanged_. This is to avoid conflicts with other potential hotlink areas on the page.
