### ISSUE TITLE
move css back into js?

### ISSUE THREAD

**Issue by dogsGhost** [dunnbro/pagination#17]
Do you think we should move hide/show responsibilities back into the javascript?
Since we're converting it to a plugin having all the code in one file will be a convenience. Also javascript inlines the styles, which will help enforce the hide/show in the case of any conflicting styles from the user.

**Comment by dunnbro** [comment]
When I tried moving the hide/show .css into the javascript, all the storySections display briefly before hide() kicks in. Any way around this?

**Comment by dogsGhost** [comment]
With the scripts loading at the bottom of the page that issue can't really be avoided.
Per conversation yesterday having the script handle this is better so the plugin isn't reliant on css, and also for situations where javascript might not load, it allows all the content to still display for the user.
