### ISSUE TITLE
minor optimizations

### ISSUE THREAD

**Issue by dogsGhost** [dunnbro/pagination#2]
- remove unneeded use of `parseInt()`
- use `.length` instead of the depreciated method `.size()`
- combine the use of `.after()` and multiple uses of `.append()` inside `loadButtons()` into one call of `.after()`
- set initial text inside `#js-pagecount` when loaded on page, then change `updatePageNumber()` to only update the number in the text rather than the whole string.

**Comment by dunnbro** [comment]
everything above, 
also changed .show() and .hide() to .css display:none or :block as appropriate

**Comment by dogsGhost** [comment]
You should be able to remove all css manipulation via javascript and add rules to `paginate.css` that will handle the show/hide for you using `.js-storySection` and `.js-currentchapter` as your css selectors.

**Comment by dunnbro** [comment]
moved css manipulation to paginate.css from paginate.js
