### ISSUE TITLE
remove global variable self

### ISSUE THREAD

**Issue by dogsGhost** [dunnbro/pagination#20]
Currently using global var `self` to maintain reference to `this` instead event listeners.
Fix so `self` is taken out of global scope and instead passed as a parameter to the event listener functions.

**Comment by dunnbro** [comment]
`self` is now passed as parameter to the event listener functions.

**Comment by dogsGhost** [comment]
I actually made a mistake here in explaining. The `self` variable doesn't have to be passed to the function called inside the handler function. The context of `this` only changes inside the handler function, functions called inside the handler function reference `this` correctly so a reference doesn't have to be passed.
