### ISSUE TITLE
scope functions to paginate object

### ISSUE THREAD

**Issue by dogsGhost** [dunnbro/pagination#3]
Currently all functions exist at the global scope. Consider changing them to methods of the `paginate` object instead. e.g. `function loadButtons() { ... }` becomes `paginate.loadButtons = function () { ... };`

**Comment by dunnbro** [comment]
limited functions' scope as specified

**Comment by dogsGhost** [comment]
`var numPages = ($('#story').children().length);` should also be declared inside `init()` so it is only calculated if `init()` is called. It should also be a property of `paginate` so it remains available to other methods.
