### ISSUE TITLE
consolidate event functions

### ISSUE THREAD

**Issue by dogsGhost** [dunnbro/pagination#4]
The four functions bound to the four buttons share a lot of functionality, the main difference being which element is be affected. Use event delegation to reduce the amount of duplicate code.

**Comment by dunnbro** [comment]
used event delegation to reduce the duplicate code

**Comment by dogsGhost** [comment]
Check the docs for [`.on()`](http://api.jquery.com/on/) and use the `selector` parameter for determining which child node of `#js-buttons` to check for. This should eliminate the test for `$target.is('input')`.
