### ISSUE TITLE
jump to start of a new section

### ISSUE THREAD

**Issue by dogsGhost** [dunnbro/pagination#6]
When a button is clicked to go to a new section, if the top of the new section is not visible in the viewport (due to section length) the page should move so the top of the section is visible for the user to begin reading the new section.

**Comment by dunnbro** [comment]
added window.scrollTo (0,0) when button is clicked to navigate to a new section/chapter

**Comment by dogsGhost** [comment]
This scrolls to the first pixel (top) of the window. We want to move to the top of the `#story` container regardless of where it is on the page. So the second value passed to `scrollTo()` should be the number of pixels `#story` is from the top of the body.

**Comment by dunnbro** [comment]
As you mentioned, linking to the id jumps to the appropriate spot on the page, so scrollTo is no longer needed.
