### ISSUE TITLE
allow passable parameters that override defaults

### ISSUE THREAD

**Issue by dogsGhost** [dunnbro/pagination#8]
Allow a user to pass settings to the `paginate` object so some defaults can be overridden if desired.
For example:

```
paginate.init({
    containerID: '#essay'
});
```

The `paginate` object would then use `#essay` everywhere `#story` is normally used, defaulting to story if no `containerID` property was passed.

**Comment by dunnbro** [comment]
Only "sectionTerm" can be set by user currently.

**Comment by dogsGhost** [comment]
Additional settings to add:
- classname used for story section, default: 'js-storySection'
- word used for url hash, default: 'section'
- classname used for current section, default: 'js-currentchapter'

**Comment by dunnbro** [comment]
Default values for story section, hash name, and current section all can be overridden.
